---
# tasks file for common/fedora
- name: Import RPM Fusion GPG Key (free)
  rpm_key:
    state: present
    key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020
  become: true
- name: Import RPM Fusion GPG Key (nonfree)
  rpm_key:
    state: present
    key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020
  become: true
- name: Install RPM Fusion (free)
  dnf:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm"
    state: present
  become: true
- name: Install RPM Fusion (nonfree)
  dnf:
    name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm"
    state: present
  become: true

- name: Create home directories
  file:
    path: "/home/{{ primary_user }}/{{ item }}"
    state: directory
    owner: "{{ primary_user }}"
    group: "{{ primary_group }}"
    mode: 0755
  with_items:
    - nginx
    - Projects

- name: Install simple programs
  dnf:
    name:
      - '@Development Tools'
      - ansible
      - bzr
      - cloc
      - dnf-plugins-core
      - filezilla
      - gcc-c++
      - gnome-terminal-nautilus
      - gnome-tweak-tool
      - gstreamer1
      - gstreamer1-plugins-base
      - htop
      - mycli
      - nano
      - pv
      - python3-libselinux
      - python3-docker
      - python3-mysql
      - redhat-rpm-config
      - ruby
      - ruby-devel
      - snapd
      - sqlite
      - sqlite-devel
      - sysfsutils
      - vim
      - vim-powerline
      - vlc
      - zsh
      - hunspell-en
      - hunspell-en-US
      - hunspell-nl
    state: present
  become: true
  retries: 5
  delay: 2
  register: dnf_result
  until: dnf_result is succeeded

- name: Create snap symlink
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link
  become: true

- name: Disable selinux
  selinux:
    state: disabled
  become: true
  when: disable_selinux

- name: Disable ipv6
  template:
    src: templates/sysctl/99-ipv6.conf
    dest: /etc/sysctl.d/99-ipv6.conf
    mode: 0644
  notify:
    - sysctl
  become: true
  when: disable_ipv6

- name: Set max_user_watches
  template:
    src: templates/idea/idea.conf
    dest: /etc/sysctl.d/idea.conf
    mode: 0644
  notify:
    - sysctl
  become: true

- name: Install openjdk
  dnf:
    name:
      - java
      - java-devel
    state: present
  become: true
  when: install_openjdk

- name: Install mariadb/mysql
  include_tasks: fedora/mysql.yml
  tags: mariadb mysql

- name: Install elasticsearch
  include_tasks: fedora/elasticsearch.yml
  tags: elasticsearch

- name: Install redis
  dnf:
    name: redis
    state: present
  become: true

- name: Start redis service
  systemd:
    name: redis
    enabled: true
    state: started
  become: true

- name: Include fedora/mailcatcher
  include_tasks: fedora/mailcatcher.yml
  tags: mailcatcher

- name: Install php
  include_tasks: fedora/php.yml
  tags: php

- name: Install nginx
  include_tasks: fedora/nginx.yml
  tags: nginx

- name: Install Node.js
  include_tasks: fedora/node.yml
  tags: node

- name: Install awscli
  include_tasks: fedora/aws.yml
  when: install_aws
  tags: aws awscli

- name: Install Docker repository
  template:
    src: templates/docker/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: 0644
  become: true
  when: install_docker
- name: Install Docker
  dnf:
    name: docker-ce
    state: present
  become: true
  when: install_docker
- name: Run docker service
  systemd:
    name: docker
    enabled: true
    state: started
  become: true
  when: install_docker
- name: Add primary user to docker group
  user:
    name: "{{ primary_user }}"
    groups: docker
    append: true
  become: true
  when: install_docker

- name: Install Google Chrome repository
  copy:
    src: files/google-chrome/google-chrome.repo
    dest: /etc/yum.repos.d/google-chrome.repo
    mode: 0644
  become: true
  when: install_chrome
- name: Install Google Chrome
  dnf:
    name: google-chrome-stable
    state: present
  become: true
  when: install_chrome
- name: Install Chrome GNOME Shell integration
  dnf:
    name: chrome-gnome-shell
    state: present
  become: true
  when: install_chrome

- name: Init /etc/sysfs.d
  file:
    path: /etc/sysfs.d
    state: directory
    mode: 0755
  become: true

- name: Set sleep mode to deep
  copy:
    content: deep
    dest: /etc/sysfs.d/mem_sleep.conf
    mode: 0644
  become: true

- name: Install flatpak apps
  include_tasks: fedora/flatpak.yml
  tags: flatpak

- name: Install Nvidia drivers
  dnf:
    name:
      - xorg-x11-drv-nvidia
      - akmod-nvidia
    state: present
  become: true
  when: install_nvidia_drivers

- name: Install n98-magerun2
  get_url:
    url: https://files.magerun.net/n98-magerun2.phar
    dest: "/home/{{ primary_user }}/.local/bin/n98-magerun2"
    mode: u=rwx,g=rx,o=rx
  when: install_magerun

- name: Include common/zsh
  include_tasks: common/zsh.yml
  tags: zsh

- name: Init shell
  user:
    name: "{{ primary_user }}"
    shell: /bin/zsh
  become: true
  tags: zsh
